#!/bin/bash -ex

EXTRA_BUILDX_ARGS=$@

if [[ "${EXTRA_BUILDX_ARGS}" == *"--load"* ]]; then
    PLATFORMS="linux/amd64"
else
    PLATFORMS="linux/amd64,linux/arm64"
fi

docker buildx build \
    --platform "${PLATFORMS}" \
    --progress=plain \
    --build-arg kafka_version=$KAFKA_VERSION \
    --build-arg scala_version=$TRAVIS_SCALA_VERSION \
    --build-arg vcs_ref=$TRAVIS_COMMIT \
    --build-arg build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    -t drewpc/kafka \
    $EXTRA_BUILDX_ARGS \
    .